# Generated by Django 4.2.6 on 2023-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile_delete_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevents',
            name='img',
            field=models.ImageField(default=' C:/Users/shrey/Downloads/Indian Medicinal Leaves Image Datasets/Medicinal plant dataset/781.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
