# Generated by Django 4.2.6 on 2023-10-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_clubevents_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubevents',
            name='img',
        ),
    ]
