# Generated by Django 4.2.6 on 2023-10-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_clubevents_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevents',
            name='edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clubevents',
            name='edesc',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='clubevents',
            name='efee',
            field=models.CharField(max_length=20),
        ),
    ]
