# Generated by Django 4.2.6 on 2023-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_clubevents_edate_alter_clubevents_edesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temail', models.CharField(max_length=30)),
            ],
        ),
    ]
