# Generated by Django 4.2.6 on 2023-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevents',
            name='cdesc',
            field=models.CharField(default='hi', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubevents',
            name='eimg',
            field=models.CharField(default=' https://upload.wikimedia.org/wikipedia/en/6/68/Chaitanya_Bharathi_Institute_of_Technology_logo.png', max_length=400),
            preserve_default=False,
        ),
    ]
